### ISSUE TITLE
Generation won't work with python >= 3.10

### ISSUE THREAD

**Issue by fblanchetNaN** [QCoDeS/qcodes_generate_test_db#8]
Due to:

https://docs.python.org/3/whatsnew/3.3.html#collections
https://docs.python.org/3/whatsnew/3.10.html#removed

dB cannot be generated from python 3.10

`ImportError: cannot import name 'Iterator' from 'collections'`

**Comment by jenshnielsen** [comment]
Thanks @fblanchetNaN 

This is indeed an issue. The versions of qcodes that were used to do this predatates that issue as well as several others.  We have pre-generated all the existing dbs and I hope that we will not need to regenerate them

If one really needs to do this it is possible to make a patch release to the old versions of qcodes and make a patch release to support this. There may be other similar issues (e.g. that old versions of qcodes are tested against versions of numpy that predates support for python 3.10 so there may also be a need to adapt to new versions of numpy etc )

**Comment by fblanchetNaN** [comment]
Actually I face that issue because I need DB to figure out why the qcodes CI failed on a PR and not locally. I think it will not be an issue if you generate some artifacts (and redirect to them in tests needed them (*)) containing DB for testing instead of just providing a code to generate them that can be outdated.

A solution can be to explicitly document which python versions should be used for each DB version, or to write a script using pyenv and pip to force generation with specific versions of python and dependencies.

(*) On a fresh installation, `pytest -rsx` says:
`SKIPPED [...] No db-file fixtures found. You can generate test db-files using the scripts in the https://github.com/QCoDeS/qcodes_generate_test_db/`

**Comment by jenshnielsen** [comment]
> Actually I face that issue because I need DB to figure out why the qcodes CI failed on a PR and not locally. I think it will not be an issue if you generate some artifacts (and redirect to them in tests needed them (*)) containing DB for testing instead of just providing a code to generate them that can be outdated.

That is more or less what we do. The fixtures are here https://github.com/QCoDeS/qcodes_db_fixtures they are added as a git submodule of qcodes

> (*) On a fresh installation, pytest -rsx says:
SKIPPED [...] No db-file fixtures found. You can generate test db-files using the scripts in the https://github.com/QCoDeS/qcodes_generate_test_db/

As far as I remember there is one test that tries to upgrade from the current version to current version + 1 which is always skipped. That should probably be fixed

**Comment by fblanchetNaN** [comment]
> That is more or less what we do. The fixtures are here https://github.com/QCoDeS/qcodes_db_fixtures they are added as a git submodule of qcodes

I saw that module, but maybe the message 
`No db-file fixtures found. You can generate test db-files using the scripts in the https://github.com/QCoDeS/qcodes_generate_test_db/`
Should refer to that repo and recommends doing a `git submodule update --init`

And https://github.com/QCoDeS/Qcodes/blob/master/CONTRIBUTING.rst should recommend doing a `clone` with `--recurse-submodules`.
